name: Validate Docker Compose YAML

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up folders
        #add any folders you want to check in the folders.txt
        run: |
          echo "RabbitMQ" > folders.txt
      - name: Find Docker Compose files
        run: |
          while read -r folder; do
            find . -path "*/$folder/*" -name "docker-compose*.yml" -print0 | xargs -0 -n1 dirname | sort -u >> docker-compose-files.txt
          done < folders.txt
      - name: Print Docker Compose files
        run: |
          while read -r file; do
            echo "Checking Docker Compose file: $file/docker-compose.yml"
          done < docker-compose-files.txt
      - name: Validate Docker Compose files
        run: |
          while read -r file; do
            docker-compose -f "$file/docker-compose.yml" config --quiet
            if [ $? -ne 0 ]; then
              echo "Error: invalid Docker Compose file found in $file"
              exit 1
            fi
          done < docker-compose-files.txt
